version: '2'
services:
  nginx:
    image: newa/mynewapp:0.3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      traefik.frontend.rule: "Host:www.mynewapp.poc.local"
      traefik.port: 80
      traefik.enable: 'true'
