version: '2'
services:
  nginx:
    image: newa/myoldapp:0.3
    stdin_open: true
    tty: true
    ports: 2080/80
    labels:
      io.rancher.container.pull_image: always
      traefik.frontend.rule: "Host:www.myoldapp.poc.local"
      traefik.port: ’2080’
      traefik.enable: 'true'
